### PR TITLE
documentation: overriding `render_swagger` for different response type

### PR DESCRIPTION
**Pull request by SmartHoneybee**
In reference to #78.

### CODE REVIEW

**Comment by jhthorsen** [comment]
Thanks! I liked the example in #78 better, so I used that one.

I also can't take this PR, since I could not find any author information in the commit.

**Comment by SmartHoneybee** [comment]
Glad that some of it seems useful to you.
> I also can't take this PR, since I could not find any author information in the commit.

I am sorry, but I do not know what you are talking about. Should I do something? (What?)

**Comment by jhthorsen** [comment]
"SmartHoneybee" does not have any name or email associated with the account that I can see. It also seems like you haven't set up your local git config:

https://help.github.com/articles/set-up-git/

**Comment by SmartHoneybee** [comment]
Ah, okay (thank you!) - I like it this way, actually.
Wondering why you would need to know my name licenses are the only reason I can up with at the moment. IANAL, but releasing the stuff I commit to this repository into the public domain should fix this problem, right? (Therefore, just to make it explicit:) The things (former, this and later) I send to this repository (as commits, issues, ... whatever) are released into the public domain.

I hope this helps. 
Please tell me if it does not. 
Sorry, for the inconveniences!

**Comment by jhthorsen** [comment]
I'm really not sure how this works :confused:

No need to be sorry. I greatly appreciate the effort of any code contribution! :+1:

**Pull request closed without merging**
